### PR TITLE
Changes in person.py

### PR DESCRIPTION
**Pull request by johnkegz**
comparing master and develop to make travis run the tests Please review @ongwech@BarnaTB@nuwagalb. index.html in the root directory, css in the css folder, signin.py and test_signin.py in the model folder

### CODE REVIEW

**Comment by johnkegz** [comment]
please review @BarnaTB@nuwagalb@ongwech signin.py and test_signin.py in model folder index file in the root directory and css file in the css folder

**Comment by johnkegz** [comment]
Please review @ongwech @BarnaTB @nuwagalb . index.html in the root directory, css in the css folder, signin.py and test_signin.py in the model folder

**Review by nuwagalb — COMMENTED** [review]
looks good

**Review by nuwagalb — COMMENTED** [review]
looks like you've figured out how to build from the develop branch

**Pull request merged**
